/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Garits.GUIForms.Panels;

/**
 *
 * @author ZX-MAC
 */
public class FranchiseePanel extends javax.swing.JPanel {

    /**
     * Creates new form Franchisee
     */
    public FranchiseePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Operations = new javax.swing.JPanel();
        CreateJobButton = new javax.swing.JButton();
        SearchJobButton = new javax.swing.JButton();
        PrintJobButton = new javax.swing.JButton();
        CreateInvoiceButton = new javax.swing.JButton();
        PrintInvoiceButton = new javax.swing.JButton();
        SearchInvoiceButton = new javax.swing.JButton();
        CreateReportButton = new javax.swing.JButton();
        SearchReportButton = new javax.swing.JButton();
        PrintReportButton = new javax.swing.JButton();
        StockControl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        CustomerAccounts = new javax.swing.JPanel();
        CreateCustomerButton = new javax.swing.JButton();
        AlterCustomerButton = new javax.swing.JButton();
        AlterDiscountButton = new javax.swing.JButton();
        CreateDiscountButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(662, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Operations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Stock Control");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        Operations.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Operations.setPreferredSize(new java.awt.Dimension(430, 111));

        CreateJobButton.setText("Create Job");
        CreateJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJobButtonActionPerformed(evt);
            }
        });

        SearchJobButton.setText("Search Job");
        SearchJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchJobButtonActionPerformed(evt);
            }
        });

        PrintJobButton.setText("Print Job");

        CreateInvoiceButton.setText("CreateInvoice");

        PrintInvoiceButton.setText("PrintInvoice");
        PrintInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintInvoiceButtonActionPerformed(evt);
            }
        });

        SearchInvoiceButton.setText("SearchInvoice");

        CreateReportButton.setText("CreateReport");

        SearchReportButton.setText("SearchReport");

        PrintReportButton.setText("PrintReport");

        javax.swing.GroupLayout OperationsLayout = new javax.swing.GroupLayout(Operations);
        Operations.setLayout(OperationsLayout);
        OperationsLayout.setHorizontalGroup(
            OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PrintJobButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateJobButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchJobButton, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperationsLayout.createSequentialGroup()
                        .addComponent(CreateInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(SearchInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OperationsLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(CreateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(SearchReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PrintReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        OperationsLayout.setVerticalGroup(
            OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperationsLayout.createSequentialGroup()
                        .addComponent(CreateReportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchReportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrintReportButton))
                    .addGroup(OperationsLayout.createSequentialGroup()
                        .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateInvoiceButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateJobButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OperationsLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(SearchJobButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperationsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchInvoiceButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(OperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrintJobButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrintInvoiceButton))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(Operations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 140));

        StockControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("LaunchStockManager");

        javax.swing.GroupLayout StockControlLayout = new javax.swing.GroupLayout(StockControl);
        StockControl.setLayout(StockControlLayout);
        StockControlLayout.setHorizontalGroup(
            StockControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockControlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        StockControlLayout.setVerticalGroup(
            StockControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockControlLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        add(StockControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 260, 120));

        CustomerAccounts.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CreateCustomerButton.setText("Create Customer Account");

        AlterCustomerButton.setText("Alter Customer Account");

        AlterDiscountButton.setText("Alter DiscountPlan");

        CreateDiscountButton.setText("Create DiscountPlan");

        javax.swing.GroupLayout CustomerAccountsLayout = new javax.swing.GroupLayout(CustomerAccounts);
        CustomerAccounts.setLayout(CustomerAccountsLayout);
        CustomerAccountsLayout.setHorizontalGroup(
            CustomerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerAccountsLayout.createSequentialGroup()
                .addGroup(CustomerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateCustomerButton)
                    .addComponent(AlterCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(CustomerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateDiscountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlterDiscountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CustomerAccountsLayout.setVerticalGroup(
            CustomerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerAccountsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(CustomerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateCustomerButton)
                    .addComponent(AlterDiscountButton))
                .addGap(18, 18, 18)
                .addGroup(CustomerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlterCustomerButton)
                    .addComponent(CreateDiscountButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(CustomerAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 410, 120));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Customer Account");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CreateJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJobButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateJobButtonActionPerformed

    private void SearchJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchJobButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchJobButtonActionPerformed

    private void PrintInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintInvoiceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterCustomerButton;
    private javax.swing.JButton AlterDiscountButton;
    private javax.swing.JButton CreateCustomerButton;
    private javax.swing.JButton CreateDiscountButton;
    private javax.swing.JButton CreateInvoiceButton;
    private javax.swing.JButton CreateJobButton;
    private javax.swing.JButton CreateReportButton;
    private javax.swing.JPanel CustomerAccounts;
    private javax.swing.JPanel Operations;
    private javax.swing.JButton PrintInvoiceButton;
    private javax.swing.JButton PrintJobButton;
    private javax.swing.JButton PrintReportButton;
    private javax.swing.JButton SearchInvoiceButton;
    private javax.swing.JButton SearchJobButton;
    private javax.swing.JButton SearchReportButton;
    private javax.swing.JPanel StockControl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
