/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Garits.GUIForms.Panels;

import Garits.GUIForms.Stock.AddPart;
import Garits.GUIForms.Stock.ChangeThresholdLevel;
import Garits.GUIForms.Stock.CreatePartsOrder;
import Garits.GUIForms.Stock.FindPart;
import Garits.GUIForms.Stock.PrintPartsOrder;
import Garits.GUIForms.Stock.RemovePart;
import Garits.GUIForms.Stock.SearchPartsOrder;
import Garits.GUIForms.StockControl.CreateStockReport;
import Garits.GUIForms.StockControl.PrintStockReport;
import Garits.GUIForms.StockControl.SearchStockReport;

/**
 *
 * @author Akash
 */
public class StockPanel extends javax.swing.JPanel {

    /**
     * Creates new form StockPanel
     */
    public StockPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FindPartButton = new javax.swing.JButton();
        AddPartButton = new javax.swing.JButton();
        RemovePartButton = new javax.swing.JButton();
        ThresholdLevelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CreatePartsOrderButton = new javax.swing.JButton();
        SearchPartsOrderButton = new javax.swing.JButton();
        PrintPartsOrderButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SearchStockReportButton = new javax.swing.JButton();
        PrintStockReportButton = new javax.swing.JButton();
        UpdateStockReportButton = new javax.swing.JButton();
        CreateStockReportButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FindPartButton.setText("Find Part");
        FindPartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPartButtonActionPerformed(evt);
            }
        });

        AddPartButton.setText("Add Part");
        AddPartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPartButtonActionPerformed(evt);
            }
        });

        RemovePartButton.setText("Remove Part");
        RemovePartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePartButtonActionPerformed(evt);
            }
        });

        ThresholdLevelButton.setText("Threshold Level");
        ThresholdLevelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThresholdLevelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddPartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(FindPartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RemovePartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ThresholdLevelButton)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindPartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPartButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemovePartButton)
                    .addComponent(ThresholdLevelButton))
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CreatePartsOrderButton.setText("Create Parts Order");
        CreatePartsOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePartsOrderButtonActionPerformed(evt);
            }
        });

        SearchPartsOrderButton.setText("Search Parts Order");
        SearchPartsOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPartsOrderButtonActionPerformed(evt);
            }
        });

        PrintPartsOrderButton.setText("Print Parts Order");
        PrintPartsOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintPartsOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PrintPartsOrderButton)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CreatePartsOrderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchPartsOrderButton)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreatePartsOrderButton)
                    .addComponent(SearchPartsOrderButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(PrintPartsOrderButton)
                .addGap(30, 30, 30))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SearchStockReportButton.setText("Search Stock Report");
        SearchStockReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStockReportButtonActionPerformed(evt);
            }
        });

        PrintStockReportButton.setText("Print Stock Report");
        PrintStockReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintStockReportButtonActionPerformed(evt);
            }
        });

        UpdateStockReportButton.setText("Update Stock Report");

        CreateStockReportButton.setText("Create Stock Report");
        CreateStockReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateStockReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PrintStockReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateStockReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateStockReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchStockReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchStockReportButton)
                    .addComponent(CreateStockReportButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateStockReportButton)
                    .addComponent(PrintStockReportButton))
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("WELCOME TO STOCK MANAGER");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Parts Operations");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Parts Order");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Stock Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(266, 266, 266))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FindPartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPartButtonActionPerformed
        // TODO add your handling code here:
        FindPart findP = new FindPart();
        findP.show();
    }//GEN-LAST:event_FindPartButtonActionPerformed

    private void ThresholdLevelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThresholdLevelButtonActionPerformed
        // TODO add your handling code here:
        ChangeThresholdLevel changeT = new ChangeThresholdLevel();
        changeT.show();
    }//GEN-LAST:event_ThresholdLevelButtonActionPerformed

    private void CreatePartsOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePartsOrderButtonActionPerformed
        // TODO add your handling code here:
        CreatePartsOrder createPo = new CreatePartsOrder();
        createPo.show();
    }//GEN-LAST:event_CreatePartsOrderButtonActionPerformed

    private void CreateStockReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateStockReportButtonActionPerformed
        // TODO add your handling code here:
        CreateStockReport createSr = new CreateStockReport();
        createSr.show();
    }//GEN-LAST:event_CreateStockReportButtonActionPerformed

    private void AddPartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPartButtonActionPerformed
        // TODO add your handling code here:
        AddPart addP = new AddPart();
        addP.show();
    }//GEN-LAST:event_AddPartButtonActionPerformed

    private void RemovePartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePartButtonActionPerformed
        // TODO add your handling code here:
        RemovePart removeP = new RemovePart();
        removeP.show();
    }//GEN-LAST:event_RemovePartButtonActionPerformed

    private void SearchPartsOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPartsOrderButtonActionPerformed
        // TODO add your handling code here:
        SearchPartsOrder searchPo = new SearchPartsOrder();
        searchPo.show();
    }//GEN-LAST:event_SearchPartsOrderButtonActionPerformed

    private void PrintPartsOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintPartsOrderButtonActionPerformed
        // TODO add your handling code here:
        PrintPartsOrder printPo = new PrintPartsOrder();
        printPo.show();
    }//GEN-LAST:event_PrintPartsOrderButtonActionPerformed

    private void SearchStockReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStockReportButtonActionPerformed
        // TODO add your handling code here:
        SearchStockReport searchSr = new SearchStockReport();
        searchSr.show();
    }//GEN-LAST:event_SearchStockReportButtonActionPerformed

    private void PrintStockReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintStockReportButtonActionPerformed
        // TODO add your handling code here:
        PrintStockReport printSr = new PrintStockReport();
        printSr.show();
    }//GEN-LAST:event_PrintStockReportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPartButton;
    private javax.swing.JButton CreatePartsOrderButton;
    private javax.swing.JButton CreateStockReportButton;
    private javax.swing.JButton FindPartButton;
    private javax.swing.JButton PrintPartsOrderButton;
    private javax.swing.JButton PrintStockReportButton;
    private javax.swing.JButton RemovePartButton;
    private javax.swing.JButton SearchPartsOrderButton;
    private javax.swing.JButton SearchStockReportButton;
    private javax.swing.JButton ThresholdLevelButton;
    private javax.swing.JButton UpdateStockReportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
